# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('code', models.CharField(blank=True, max_length=80, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('upper_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['-id'],
            },
        ),
    ]
