# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'type',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='code',
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuType'),
        ),
    ]
